### ISSUE TITLE
0.035 .NET 7

### ISSUE THREAD

**Issue by asumos** [turtle-insect/DQB2#10]
Application fails to load even with .net7 installed 

win11

![Screenshot 2022-11-20 150015](https://user-images.githubusercontent.com/22756463/202923437-c4e2a2b5-9a87-4fe2-9e79-bcb050749d3d.png)

**Comment by turtle-insect** [comment]
Oh
I haven't updated to windows 11 yet.
Install this and it won't start?

https://dotnet.microsoft.com/en-us/download/dotnet/7.0

**Comment by asumos** [comment]
okay that install worked, the application when errors out takes me to a different installer that once installed doesn't get recognized. thank you
