### ISSUE TITLE
Editing block placements?

### ISSUE THREAD

**Issue by default-kramer** [turtle-insect/DQB2#11]
This is not an issue. I just want to chat.

I would love to be able to programmatically edit the block placements on my home island or on a buildertopia. I am a programmer and have been considering attempting this. I'm just wondering if you've thought about this (or maybe even attempted it) and have any wisdom to share. (And I'm not even sure that save file editing would be the best way to do this. Maybe full-on modding/cracking would be better)

For context, here is my motivation: Imagine being able to programmatically construct whatever you want! I could write algorithms to generate terrain, algorithms to add plants to existing terrain, algorithms to add buildings, algorithms to add interior decoration to existing buildings... And obviously community sharing would be a natural consequence. Imagine someone asking "That's a beautiful landscape, how did you make it?" And the answer is "I used `RollingHillsV3(maxSlope: 1, minPlateauSize: 12, seed: 4805)`, then applied `FrozenLakes(minWidth: 5, maxWidth: 22, maxDepth: 5, seed: 962)`, and finally applied `PineForest(normalDensity: 0.13, groveDensity: 0.74, groveProbability: 0.05)`."

**Comment by turtle-insect** [comment]
Interesting attempt.

**Comment by turtle-insect** [comment]
My past analysis of the results

https://github.com/turtle-insect/DQB2/blob/1d384d6f94caf54c4347e7757a71e7c1b3c345fe/STGDAT/ViewModel.cs#L69

**Comment by turtle-insect** [comment]
If you are generating terrain, it may be helpful

https://github.com/turtle-insect/DQB2/blob/5a8a4770c52cedfff05c2d23d500a0bdc11767e6/STGDAT/ViewModel.cs#L161

**Comment by default-kramer** [comment]
Thank you! I'll poke around with this when I have some time.
