### ISSUE TITLE
[Request] Allow to give player "Diving Flippers" (And edit stamina)

### ISSUE THREAD

**Issue by Sapphire645** [turtle-insect/DQB2#17]
The Diving Flippers are an unused item that allows the player to swim across the water
![image](https://github.com/turtle-insect/DQB2/assets/167467641/0e44c39c-be08-4665-8a53-aea474ca0889)
The adress containing the Windbraker flag also contains the Diving Flippers flag. The debug build shows what all of the bits in this area mean. 
![image](https://github.com/turtle-insect/DQB2/assets/167467641/7ff3e24f-cd51-47ec-958a-e0b025e72390)
I don't know what all the other items do, they seem to be named after accesories from the first game.

The Diving Flippers are a very useful item for sea travel. Being able to equip it would be really cool. Could this be implemented?

The adress right before these flags also hold the Stamina and Max Stamina.
![image](https://github.com/turtle-insect/DQB2/assets/167467641/0ee870aa-6267-478e-9cbf-0731b59ec2f7)
Increasing Max Stamina could be a cool feature to have as well.

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/DQB2/commit/ed2760f0890a55ef47ef7a73200e09c9ef266658

**Comment by turtle-insect** [comment]
thank you
https://github.com/turtle-insect/DQB2/releases/tag/0.043

**Comment by Sapphire645** [comment]
Thank _you!_

**Comment by turtle-insect** [comment]
Other skills were not found to be effective.
Maybe it is something that increases the basic value of the main character.
