### ISSUE TITLE
Add filtering to skip empty indices (Linkdata browser)

### ISSUE THREAD

**Issue by Sapphire645** [turtle-insect/DQB2#18]
**Reason:**

The debug build of the game shows files with numbers.
![image](https://github.com/user-attachments/assets/7aaf46ff-ae31-4462-888e-50424462f185)

Unfortunately, they do not seem to correspond to the indices in the Linkdata browser.

My theory is that the game might skip empty indices when showing the numbers. I don't know for certain, but I want to check anyways.

Something like this?
![image](https://github.com/user-attachments/assets/837f320b-2cba-4372-b205-7fe4b1889bec)

It would also help with future game modding.

Could this be implemented?

**Comment by turtle-insect** [comment]
5c9ef97068c9a3949fe6d77284e9766693988456

Does it meet your needs?

**Comment by Sapphire645** [comment]
Yes! I have to do some testing with it before reaching conclusions. Thank you!
