### ISSUE TITLE
Unlock Main Islands Support (CMN.DAT)

### ISSUE THREAD

**Issue by Sapphire645** [turtle-insect/DQB2#19]
This is where the game stores the state of the main islands:

0x53D -> STGDAT01 - IOA
0x545 -> STGDAT02 - FURROWFIELD
0x54D -> STGDAT03 - KHRUMBUL-DUN
0x555 -> STGDAT04 - MOONBROOKE
0x55D -> STGDAT05 - MALHALLA
0x565 -> STGDAT06 -
0x56D -> STGDAT07 - 
0x575 -> STGDAT08 - 
0x57D -> STGDAT09 - ANGLER'S ISLE
0x585 -> STGDAT10 - SKELKATRAZ
0x58D -> STGDAT11 - 
0x595 -> STGDAT12 -
0x59D -> STGDAT13 - 
0x5A5 -> STGDAT14 - BATTLE ATOLL
0x5AD -> STGDAT15 - 
0x5B5 -> STGDAT16 - 
0x5BD -> STGDAT17 - 
0x5C5 -> STGDAT18 - EXPLORER SHORE
0x5CD -> STGDAT19 - 
0x5D5 -> STGDAT20 -
0x5DD -> STGDAT21 - 
0x5E5 -> STGDAT22 - 
0x5ED -> STGDAT23 - 
0x5F5 -> STGDAT24 - 
0x5FD -> STGDAT25 - 
0x605 -> STGDAT26 - 
0x60D -> STGDAT27 - 
0x615 -> STGDAT28 -
0x61D -> STGDAT29 - 
0x625 -> STGDAT30 - 
0x62D -> STGDAT31 - 

The values mean:
0000 ---1 : Icon exists in the map (0x01)
0000 --1- : Can be travelled to (0x03)
These 2 I do not know
0000 -1-- : (Has not been travellet to yet/ new ?)
0000 1--- : (Has been travelled to? Main islands (except IoA) all have 0x0B or 0x08 on completed save)

**Battle Atoll and Skelkatraz can be unlocked and travelled to:**
![image](https://github.com/user-attachments/assets/ce42be97-9f68-4d4a-8de0-9c9fb43cb1f5)

**Comment by turtle-insect** [comment]
Great work

**Comment by turtle-insect** [comment]
support
1d6c4a3e22939d15f460d9938fe5bcd7276c21d3

**Comment by Sapphire645** [comment]
I made this infographic, it might be useful?
![Island_Infographic2](https://github.com/user-attachments/assets/ed372de4-94b0-44a3-a32e-d5f8161891ce)
![image](https://github.com/user-attachments/assets/1d056ea9-9510-43ce-af72-1852efa6a9ea)
(Tried to translate it)
