### ISSUE TITLE
4th hidden "Place" in IoA

### ISSUE THREAD

**Issue by Sapphire645** [turtle-insect/DQB2#21]
With debug tools I found this
![image](https://github.com/user-attachments/assets/4313e172-3e73-49b9-be1a-5502b7ae302c)
The beach is a valid NPC place.

NPCs can be assigned to rooms if they are in the "beach" place (ID4)
![tumblr_a357debffa9d5f864c8671cb176388bf_3da52a68_2048](https://github.com/user-attachments/assets/859c1177-76a3-4edb-a2bb-acb9af106177)

They act normally, like in any other "place"
![tumblr_b63e03f07aea40e104ba87b474f134c3_34ebe628_2048](https://github.com/user-attachments/assets/e24dbd8e-eeab-4867-9ff3-34b1a251fa09)

Could an option to set their place to the beach be added?
![image](https://github.com/user-attachments/assets/2d4d2cfe-c196-451d-a719-b8d307fc1cb2)

**Comment by Sapphire645** [comment]
https://bsky.app/profile/miyt645.bsky.social/post/3lcy4z743js2d

Fifth area discovered!

**Comment by turtle-insect** [comment]
great work!

**Comment by turtle-insect** [comment]
hmm
I couldn't confirm that it works here.

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/DQB2/commit/c3034486d2c22b5e46cbe14c6d96da55ca93f989
