### ISSUE TITLE
LINKDATA Crash when importing file after filtering

### ISSUE THREAD

**Issue by Sapphire645** [turtle-insect/DQB2#22]
Sorry! I'm always bothering you! ;u;

I've always had this problem, but I've now looked into it.

Trying to import an IDX file after using the index filtering crashes the program.

![image](https://github.com/user-attachments/assets/475f4498-1b9d-418f-8376-e374ab4b7e46)

I debugged to see what was the problem.

![image](https://github.com/user-attachments/assets/5b4669e0-35b9-4616-b847-c3413e885403)
The importing uses the filtered list "IDX" and tries to find the file with the absolute ID.

This makes the program crash.

This does not happen when exporting. Only importing.

Could it be fixed?

(If necessary I can send a video)

**Comment by turtle-insect** [comment]
thank you!
