### ISSUE TITLE
(LINKDATA Browser) Import .idxout files

### ISSUE THREAD

**Issue by Sapphire645** [turtle-insect/DQB2#23]
I am trying to export, then reimport uncompressed files (.idxout), but I'm not able to.
![image](https://github.com/user-attachments/assets/8c2da659-d1c3-4cb9-b9a6-01bca29b0dc3)
The option does not appear, and changing the file to .idxzrc crashes the program.

Can an "import .idxout" option be added? Thank you!

(I am working on modding dialogue cutscenes. They are stored around index 15000 on the steam release)

**Comment by turtle-insect** [comment]
> Can an "import .idxout" option be added?

I can do it.

**Comment by turtle-insect** [comment]
> (I am working on modding dialogue cutscenes.

Looking forward to it.

**Comment by turtle-insect** [comment]
Supported.
Please let me know if there are any glitches.

**Comment by turtle-insect** [comment]
while you’re at it

https://github.com/turtle-insect/DQB2/commit/63c40a4454532bc1ceca79a78e9d0a087a28ec69

**Comment by Sapphire645** [comment]
Thank you! [(Here's what I've figured out about cutscenes as of now!)](https://github.com/Sapphire645/DQB2TextEditingScripts/tree/main)

**Comment by turtle-insect** [comment]
https://gbatemp.net/threads/dragon-quest-builders-2.528161/post-8466767
