### ISSUE TITLE
(Feature Request) Add changing the appearance of player's hammer, armor and weapon

### ISSUE THREAD

**Issue by bluedogz162** [turtle-insect/DQB2#3]
You can change the appearance of the player's weapon, hammer, and armor in-game at a dressing table. This would be something to add to the editor, as certain weapons cannot be selected for appearances (War Banner, etc.)

**Comment by turtle-insect** [comment]
public Item Hammer { get; private set; } = new Item(0x6A8C6);
public Item Weapon { get; private set; } = new Item(0x6A8C2);
public Item Armmer { get; private set; } = new Item(0x6A8CA);
public Item Shield { get; private set; } = new Item(0x6A8CE);
public Item Head { get; private set; } = new Item(0x6A8D2);
public Item Accessories1 { get; private set; } = new Item(0x6A8D6);
public Item Accessories2 { get; private set; } = new Item(0x6A8DA);
public Item Accessories3 { get; private set; } = new Item(0x6A8DE);

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/DQB2/commit/929b72b00cf14cf2e4575181d59b7d1d43ce861b

**Comment by turtle-insect** [comment]
support
https://github.com/turtle-insect/DQB2/releases/tag/0.028
